services:
  - type: web
    name: django-delights
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn your_project_name.wsgi:application --bind 0.0.0.0:8000"
    autoDeploy: true